# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-29 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordrecite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMore',
            new_name='UserAttrib',
        ),
    ]
